### ISSUE TITLE
Threshold can't be 0?

### ISSUE THREAD

**Issue by nickcarenza** [the-control-group/query-swarm#5]
Can we change the queue length check to be <= so that the threshold can be set to 0? If I am understanding this right, a threshold of 0 would never trigger a populate.

https://github.com/the-control-group/query-swarm/blob/master/lib/QuerySwarm.js#L50-L51

https://github.com/the-control-group/query-swarm/blob/master/lib/Worker.js#L120-L122

**Comment by mike-marcacci** [comment]
Oh ya, that's a great point! I guess we never really had that use case, since a low threshold results in suboptimal worker utilization (at least some workers will sit there without tasks while new work is fetched). But you're right that this behavior with zero is SUPER unintuitive.

I wouldn't be too concerned about that change breaking things.
